version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:10.13.0

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: curl -o- -L https://yarnpkg.com/install.sh | bash
      - run:
          name: Install packages
          command: yarn install --frozen-lockfile
      -run:
          name: Bootstrap packages with lerna
          command: yarn lerna bootstrap
      - run:
          name: Run tests
          command: yarn test
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}

      - persist_to_workspace:
          root: ~/repo
          paths: .
  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run: yarn run build

workflows:
  version: 2
  test-build:
    jobs:
      - test
      - build
