version: 2
jobs:
  test:
    docker:
      - image: circleci/node:10.13.0
    steps:
      - checkout
      - run: npm test
  build:
    docker:
      - image: circleci/node:10.13.0
    steps:
      - checkout
      - run: npm run build
